#!/bin/bash
if [ "$1" == "--help" ]; then
cat ~/CusCom/HelpFiles/${0##*/}.help
exit
fi
echo All power devices:
upower -e
echo Battery status:
upower -i $(upower -e | grep -i "bat") | grep -E "state: | time\ to | percentage: | energy: | energy-empty: | energy-full: | energy-rate: | voltage: | capacity: "
echo AC Adapter status:
upower -i $(upower -e | grep -i "line_power") | grep -E "online:"

