#!/bin/bash
a=0
b=0
c=0
seta=false
setb=false
setc=false


if [ "$1" == "" ]
then echo "You have to enter numbers, silly." && exit 2
elif [ "$2" == "" ]
then echo "You have to enter more than one number, silly." && exit 2
elif [ "$3" == "" ]
then echo "You have to enter more than two numbers, silly." && exit 2
elif [ "$4" != "" ]
then echo "You can't enter more than three numbers, silly." && exit 2
fi

if [ $(($1 + $2)) -le $3 ]
then echo "Invalid triangle!" && exit 1
elif [ $(($2 + $3)) -le $1 ]
then echo "Invalid triangle!" && exit 1
elif [ $(($3 + $1)) -le $2 ]
then echo "Invalid triangle!" && exit 1
fi

if [ $1 -gt $2 ] && [ $1 -gt $3 ]
then c=$1
set1=true
elif [ $2 -gt $1 ] && [ $2 -gt $3 ]
then c=$2
set2=true
elif [ $3 -gt $2 ] && [ $3 -gt $1 ]
then c=$3
set3=true
fi
echo "Largest number is $c"
if [ $1 -lt $2 ] && [ $1 -lt $3 ]
then a=$1
set1=true
elif [ $2 -lt $1 ] && [ $2 -lt $3 ]
then a=$2
set2=true
elif [ $3 -lt $2 ] && [ $3 -lt $1 ]
then a=$3
set3=true
fi
echo "Smallest number is $a"
if [ $1 -lt $c ] && [ $1 -gt $a ]
then b=$1
elif [ $2 -lt $c ] && [ $2 -gt $a ]
then b=$2
elif [ $3 -lt $c ] && [ $3 -gt $a ]
then b=$3
fi
echo "Middle number is $b"


# Right triangle detection
if [ $(( $a*$a + $b*$b )) == $(( $c*$c )) ]
then echo "Right triangle!"
fi
# Obtuse detection
if [ $(( $a*$a + $b*$b )) -lt $(( $c*$c )) ]
then echo "Obtuse triangle!"
fi
# Acute detection
if [ $(( $a*$a + $b*$b )) -gt $(( $c*$c )) ]
then echo "Acute triangle!"
fi
